### ISSUE TITLE
Add button to delete simulation group

### ISSUE THREAD

**Issue by jandevaty** [storm-fsv-cvut/runoffDB_UI#38]
Simulation group does not have any button to be "deleted" (only "edit" and "add new simulation to group")
![obrazek](https://github.com/storm-fsv-cvut/runoffDB_UI/assets/64583380/1b576beb-2e37-49dd-ac76-dbee11382791)

**Comment by ppavelProkop** [comment]
Při odstranení skupiny smazat vše co je pod ní (měření, záznamy, data), nebo měření zanechat a jenom odpojit od simulace?

**Comment by jandevaty** [comment]
No to je otázka ... šlo by se uživatele zeptat? a třeba je k tomu ještě vypsat? a třeba ještě udělat checkboxy
"Přejete si ponechat připojené měření a záznamy?
[ ] povrchový odtok #xxxx
[ ] koncentrace sedimentu #xxxx"
Ponechat        Smazat vybraná měření      Smazat všechna připojená měření
???
