### ISSUE TITLE
Chyba dlouhé neaktivity - odlogování

### ISSUE THREAD

**Issue by neumama4** [storm-fsv-cvut/runoffDB_UI#51]
V případě přihlášení a dlouhé neaktivity se asi účet automaticky odloguje. Když na něco kliknu tak error 500. Píše mi to že jsem stále přihlášen a když kliknu na svoje jméno, tak dám odhlásit, přihlásím se a pak je to v pohodě. Někde to tam asi visí a pro uživatele může být matoucí.

**Comment by ppavelProkop** [comment]
Nedaří se mi to nasimulovat. Můžete prosím poslat konkrétní stránku a akci při které to pak hodí 500?

**Comment by neumama4** [comment]
Občas se ukáže že jsem odlogován, ale někdo to házelo toto:
![obrazek](https://github.com/storm-fsv-cvut/runoffDB_UI/assets/141822686/735052ad-9622-4558-9259-072730582a95)
I když dám zvounačíst stránku, tak to nejde a nevím jestli je to  tím, že tam z nějakého důvodu chybí "cs" v linku. Až na to je link totožnej. Zrovna to ve dvou panelech mám a to jsem ve čtyřech pracoval v databázi.

**Comment by neumama4** [comment]
Nevím jestli je to z konkrétní stránky, ale když mám někde rodvělanou práci a přijdu druhý den, tak když na něco kliknu, tak se občas objeví toto. Pokud nepůjde jednoduše zjistit a vyřešit, tak si dám větší pozor na to kdy se to děje, abychom ještě více upřesili, kdy se to stává.
